/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package JFrame;

/**
 *
 * @author Evistix
 */
public class Gacha extends javax.swing.JFrame {

    /**
     * Creates new form Gacha
     */
    public Gacha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        背景 = new javax.swing.JPanel();
        信息1 = new javax.swing.JLabel();
        信息2 = new javax.swing.JLabel();
        十连抽 = new javax.swing.JButton();
        返回 = new javax.swing.JButton();
        单抽 = new javax.swing.JButton();
        信息 = new javax.swing.JLabel();
        充值 = new javax.swing.JButton();
        Up = new javax.swing.JPanel();
        BackGroundLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1001, 600));

        背景.setOpaque(false);
        背景.setPreferredSize(new java.awt.Dimension(1000, 600));

        信息1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        信息1.setText("900点券");

        信息2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        信息2.setText("100点券");

        十连抽.setBackground(new java.awt.Color(153, 255, 255));
        十连抽.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        十连抽.setForeground(new java.awt.Color(0, 204, 102));
        十连抽.setText("【十连抽】");
        十连抽.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                十连抽ActionPerformed(evt);
            }
        });

        返回.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        返回.setForeground(new java.awt.Color(0, 51, 204));
        返回.setText("返回");

        单抽.setBackground(new java.awt.Color(204, 51, 255));
        单抽.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        单抽.setForeground(new java.awt.Color(255, 102, 153));
        单抽.setText("【单抽】");

        信息.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        信息.setText("这里到时候放角色信息，右边放金币");

        充值.setBackground(new java.awt.Color(255, 204, 51));
        充值.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        充值.setForeground(new java.awt.Color(255, 51, 51));
        充值.setText("充值");

        javax.swing.GroupLayout 背景Layout = new javax.swing.GroupLayout(背景);
        背景.setLayout(背景Layout);
        背景Layout.setHorizontalGroup(
            背景Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(背景Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(信息, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, 背景Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(信息2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(信息1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
            .addGroup(背景Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(背景Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(单抽, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(充值, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(139, 139, 139)
                .addGroup(背景Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(十连抽, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(返回, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        背景Layout.setVerticalGroup(
            背景Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(背景Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(信息, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(背景Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(十连抽, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(单抽, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(背景Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(信息2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(信息1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(背景Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(充值, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(返回, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );

        Up.setPreferredSize(new java.awt.Dimension(1020, 600));

        BackGroundLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backGround/b1.png"))); // NOI18N
        BackGroundLabel2.setPreferredSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout UpLayout = new javax.swing.GroupLayout(Up);
        Up.setLayout(UpLayout);
        UpLayout.setHorizontalGroup(
            UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackGroundLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        UpLayout.setVerticalGroup(
            UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackGroundLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(背景, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 20, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(背景, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void 十连抽ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_十连抽ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_十连抽ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gacha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel BackGround1;
    private javax.swing.JLabel BackGroundLabel;
    private javax.swing.JLabel BackGroundLabel1;
    private javax.swing.JLabel BackGroundLabel2;
    private javax.swing.JPanel Up;
    private javax.swing.JLabel 信息;
    private javax.swing.JLabel 信息1;
    private javax.swing.JLabel 信息2;
    private javax.swing.JButton 充值;
    private javax.swing.JButton 十连抽;
    private javax.swing.JButton 单抽;
    private javax.swing.JPanel 背景;
    private javax.swing.JButton 返回;
    // End of variables declaration//GEN-END:variables
}
